Stop splitting common operators
scala/vscode-scala-syntax pull request #275
Opened 2024-10-09 11:01 UTC by Jentsch

This PR fixes the most common operators like `->`, `:+`, `=>`, `<-`.

The cost in terms of complexety is quite high and it's still not correct 
in many cases. `>=>` is still interpreted as two comparisons and in `&=` the `&` isn't regonized as operator at all.

The change looks quite drastic, but the changes in the snaps look fine to me.

A change where I'm not sure if we want it:
```
   i -= 1
//  was:
//   ^ keyword.operator.arithmetic.scala
//    ^ keyword.operator.comparison.scala
//  now:
//   ^^ keyword.operator.scala <- 
```
One could argue, the `-` is realy the arithmetic operator here, as the
expressions `i -= 1` most of the time means `i = i - 1`.

Btw. I don't think in `i = 1` the `=` should be marked as a comparison but just as an operator.

2024-10-09 11:05 UTC, bishabosha commented
I think that because you are allowed to define `def -= (foo: Int) ...` that the interpretation is fine

2024-10-09 12:26 UTC, Jentsch commented
I changed how operators are recognized and I'll update the PR text.

2024-10-09 14:11 UTC, Jentsch commented on src/typescript/Scala.tmLanguage.ts
> +                  match: '(=|\\<|>)',
Here I think we shouln't match `=`, as a single `=` doesn't compare but defines things.

2024-10-11 08:20 UTC, tgodzik requested changes
Makes sense! You need to rebase on main to get this mergable though

2024-10-11 09:54 UTC, Jentsch commented
Done

2024-10-11 10:22 UTC, tgodzik approved these changes
Thanks!

2024-10-11 10:22 UTC, merged